env = SConscript("../godot-cpp/SConstruct", {"api_version": "4.6"})

env_shared = env.Clone()
env_shared.Append(CPPDEFINES=["VIT_EXTENSION_EXPORTS"])

library_name = "vit_extension.{}.{}.{}{}".format(
    env["platform"],
    env["target"],
    env["arch"],
    env["SHLIBSUFFIX"],
)

library = env_shared.SharedLibrary(
    target="#bin/{}".format(library_name),
    source=Glob("src/*.cpp"),
)

Default(library)
